---
# tasks file for ansible

- name: Show Hostname
  debug:
    msg: "Hostname is {{ ansible_hostname }} - {{ ansible_os_family }}"

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Clone Armory
  git:
    repo: https://github.com/galaxy3-net/armory.git
    dest: /home/vagrant/armory
    version: armory

- name: Start DHCPD
  command:
    chdir: "/home/vagrant/armory/dhcp"
    cmd: "bin/up"

- name:  CRON to update Armory
  cron:
    hour: */2
    minute: 03
    user: "vagrant"
    job: "chdir /home/vagrant/armory && git pull >> /home/vagrant/armory_cron.log"


