---
# tasks file for ansible

- name: Show Hostname
  debug:
    msg: "Hostname is {{ ansible_hostname }} - {{ ansible_os_family }}"

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

#- name: Clone Armory
#  git:
#    repo: https://github.com/galaxy3-net/armory.git
#    dest: /home/vagrant/armory
#    version: armory

- name: Clone Armory to /Armory
  git:
    repo: https://github.com/galaxy3-net/armory.git
    dest: /Armory
    version: armory

- name: Start DHCPD
  command:
    chdir: "/Armory/dhcp"
    cmd: "bin/up"

- name:  CRON to update Armory
  cron:
    name: "update_armory"
    hour: "*/2"
    minute: "03"
    user: "vagrant"
    job: "chdir /Armory && git pull >> /home/vagrant/armory_cron.log"


